source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/liangyujuan/KYModulSpecs.git'
use_frameworks!

platform :ios, '8.0'

target 'component_baseUI_iOS_Example' do
  pod 'component_baseUI_iOS', :path => '../'

  target 'component_baseUI_iOS_Tests' do
    inherit! :search_paths

    
  end
end
